import { User } from '../types/user';

export const INITIAL_MOCK_USERS: User[] = [
  {
    id: 'usr-1',
    firstName: 'Jack',
    lastName: 'Bennett',
    name: 'Jack Bennett',
    email: 'jackb@omp.com',
    personalEmail: 'jackb@gmail.com',
    employeeId: 'EMP-557',
    role: 'Operator',
    status: 'Active',
    members: 'Platform Core',
    phone: '+91 8902929062',
    nationality: 'Japan',
    gender: 'Male',
    dateOfBirth: '2003-06-20',
    joinedDate: 'Fri, Sep 11, 2026'
  },
  {
    id: 'usr-2',
    firstName: 'Sarah',
    lastName: 'Al-Mansoor',
    name: 'Sarah Al-Mansoor',
    email: 'sarah.mansoor@vopx.ai',
    personalEmail: 's.mansoor@outlook.com',
    employeeId: 'EMP-1048',
    role: 'Administrator',
    status: 'Active',
    members: 'Executive Team',
    phone: '+974 5512 3456',
    nationality: 'Qatar',
    gender: 'Female',
    dateOfBirth: '1992-04-14',
    joinedDate: 'Mon, Jan 15, 2024'
  },
  {
    id: 'usr-3',
    firstName: 'Michael',
    lastName: 'Vance',
    name: 'Michael Vance',
    email: 'michael.vance@vopx.ai',
    personalEmail: 'm.vance@yahoo.com',
    employeeId: 'EMP-1082',
    role: 'Technical Manager',
    status: 'Away',
    members: 'Engineering',
    phone: '+1 415 892 1044',
    nationality: 'United States',
    gender: 'Male',
    dateOfBirth: '1988-11-03',
    joinedDate: 'Wed, Mar 20, 2024'
  },
  {
    id: 'usr-4',
    firstName: 'Elena',
    lastName: 'Rostova',
    name: 'Elena Rostova',
    email: 'elena.rostova@vopx.ai',
    personalEmail: 'elena.rostova@gmail.com',
    employeeId: 'EMP-1109',
    role: 'Inspector',
    status: 'Do Not Disturb',
    members: 'Quality Assurance',
    phone: '+44 7700 900321',
    nationality: 'United Kingdom',
    gender: 'Female',
    dateOfBirth: '1995-08-22',
    joinedDate: 'Thu, May 09, 2024'
  },
  {
    id: 'usr-5',
    firstName: 'David',
    lastName: 'Chen',
    name: 'David Chen',
    email: 'david.chen@vopx.ai',
    personalEmail: 'dchen.sg@gmail.com',
    employeeId: 'EMP-1140',
    role: 'Viewer',
    status: 'Active',
    members: 'Operations',
    phone: '+65 9123 4567',
    nationality: 'Singapore',
    gender: 'Male',
    dateOfBirth: '1997-12-05',
    joinedDate: 'Tue, Jul 16, 2024'
  }
];
